language: python

python:
 - "3.6"
services: mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=app.settings
  - export PYTHONPATH=$HOME/builds/smcuenca2/core-medical
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt

script:
  - python manage.py runserver
