language: python

python:
 - "3.6"
services: mysql

before_install:
  - docker version
  - docker-compose version
install:
  - docker-compose -f docker-compose.yml build

script:
  - docker-compose up
