version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: umls
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    build: .
    command: python manage.py runserver localhost:8000
    volumes:
      - .:/core-medical
    ports:
      - "8000:8000"
    depends_on:
      - db
