version: '3.1'

services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: jorge.malla
      POSTGRES_PASSWORD: xxxx
      POSTGRES_DB: core-medical

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core-medical
    ports:
      - "8000:8000"
    depends_on:
      - db
