# Generated by Django 2.1.2 on 2018-11-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupatc',
            name='type',
            field=models.CharField(choices=[('ALFA', 'ALFA'), ('NUMERIC', 'NUMERICO')], default='ALFA', max_length=25),
        ),
    ]
