# Generated by Django 2.1.2 on 2018-11-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnmb', '0003_auto_20181122_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionlevel',
            name='physic',
        ),
        migrations.AddField(
            model_name='physic',
            name='prescription_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physics', to='cnmb.PrescriptionLevel'),
            preserve_default=False,
        ),
    ]
